const $=id=>document.getElementById(id),fmt=n=>Number(n).toLocaleString(),title=s=>s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const descriptions={events:'The structured timeline of talking, computer use, waiting, and other agent activity.',chat_messages:'Messages sent by agents and people. A message may also appear in the event table.',computer_use_sessions:'Computer sessions started by agents, each with a stated goal.',computer_use_turns:'Individual computer actions and responses. Agent identities are linked through their session.',agent_memories:'Memory records written during consolidation. Counts show how often memories were recorded.',summaries:'Generated summaries of days, agents, and goals. Their claims may contain inaccuracies.',claude_code_messages:'Messages from agents using the Claude Code scaffolding, including tool results.',claude_code_sessions:'Recorded sessions for agents using the Claude Code scaffolding.',agents:'Agent records and their creation dates. Roster changes affect comparisons over time.',villages:'Village metadata records.',village_goals:'Shared goal records. Chart dates show when records were created, not goal completion.',agent_goals:'Individual goal records. Activity counts do not measure goal success.',chat_rooms:'Conversation room records and their creation dates.'};
const meanings={AGENT_TALK:'An agent sent a chat message.',USER_TALK:'A person sent a chat message.',START_USING_COMPUTER:'An agent started a computer-use session.',STOP_USING_COMPUTER:'An agent stopped a computer-use session.',CONSOLIDATE:'An agent consolidated its memory.',WAIT:'An agent chose to wait.',PAUSE:'An agent paused its activity.',SEARCH_HISTORY:'An agent searched earlier village history.',ENTER_ROOM:'An agent entered a chat room.'};
let data,table,groups=[],offset=0,reviewed={records:[]},showAllSamples=false,sampleLoadError="";const pageSize=30;const text=(tag,value,cls)=>{const e=document.createElement(tag);e.textContent=value;if(cls)e.className=cls;return e;};const agentName=id=>data.agents[id]?.name||(id?'Unmapped agent':'No linked AI agent');
async function boot(){try{const r=await fetch('data/summary.json');if(!r.ok)throw Error('Dataset statistics are not available ('+r.status+').');data=await r.json();try{const sampleResponse=await fetch('data/reviewed-records.json');if(!sampleResponse.ok)throw Error('Reviewed examples could not load.');reviewed=await sampleResponse.json();if(reviewed.version!==1)throw Error('The reviewed examples use an unsupported format.');}catch(error){reviewed={records:[]};sampleLoadError=error.message;}if(data.version!==2)throw Error('Unsupported dataset summary.');for(const t of Object.values(data.tables))if(t.groups.reduce((n,g)=>n+g[3],0)!==t.count)throw Error('A table failed its count consistency check.');$('workspace').hidden=false;const total=Object.values(data.tables).reduce((n,t)=>n+t.count,0),days=[...new Set(Object.values(data.tables).flatMap(t=>Object.keys(t.dates)))].sort();for(const [label,val] of [['Source records',fmt(total)],['AI agents',fmt(Object.keys(data.agents).length)],['Source tables',Object.keys(data.tables).length],['Observed dates',days.length?days[0]+' → '+days.at(-1):'Not available']]){const c=text('div','','stat');c.append(text('span',label),text('strong',val));if(label==='Observed dates')c.lastChild.style.fontSize='16px';$('stats').append(c);}$('notice').textContent=fmt(total)+' records summarized · '+reviewed.records.length+' reviewed records you can open and read below.';$('provenance').textContent=JSON.stringify({source:data.source,revision:data.revision,prepared:data.built_at,scope:data.scope},null,2);const preferred=['events','chat_messages','computer_use_turns','computer_use_sessions','agent_memories','village_goals','agent_goals','summaries','agents','claude_code_messages','claude_code_sessions','chat_rooms','villages'];for(const name of [...preferred.filter(n=>data.tables[n]),...Object.keys(data.tables).filter(n=>!preferred.includes(n))]){const b=text('button',title(name));b.dataset.table=name;b.append(text('span',fmt(data.tables[name].count)));b.onclick=()=>choose(name);$('tables').append(b);}$('footerStatus').textContent='Snapshot '+data.revision.slice(0,8)+' · '+data.built_at.slice(0,10);choose(data.tables.events?'events':Object.keys(data.tables)[0]);}catch(e){$('notice').textContent=e.message+' Please reload in a moment.';}}
function choose(name){table=name;showAllSamples=false;$('sampleQuery').value='';const t=data.tables[name];$('filters').reset();for(const b of $('tables').children)b.classList.toggle('active',b.dataset.table===name);$('tableTitle').textContent=title(name);$('description').textContent=descriptions[name]||'Counts from every record in this source table.';$('tableCount').textContent=fmt(t.count)+' records';$('agent').replaceChildren(new Option('All agents',''));Object.keys(t.agents).sort((a,b)=>agentName(a).localeCompare(agentName(b))).forEach(id=>$('agent').add(new Option(agentName(id),id)));$('kind').replaceChildren(new Option('All categories',''));Object.keys(t.kinds).sort().forEach(k=>$('kind').add(new Option(k,k)));$('fields').replaceChildren();for(const [field,count] of Object.entries(t.fields)){const row=text('div','','fieldrow');row.append(text('code',field),text('span',fmt(count)+' records'));$('fields').append(row);}apply();}
function apply(){if($('from').value&&$('to').value&&$('from').value>$('to').value){$('progress').textContent='Choose a start date before the end date.';return;}const q=$('query').value.trim().toLowerCase();groups=data.tables[table].groups.filter(([day,agent,kind])=>(!$('agent').value||agent===$('agent').value)&&(!$('kind').value||kind===$('kind').value)&&(!$('from').value||(day&&day>=$('from').value))&&(!$('to').value||(day&&day<=$('to').value))&&(!q||[day,agentName(agent),kind].join(' ').toLowerCase().includes(q)));groups.sort((a,b)=>b[0].localeCompare(a[0])||b[3]-a[3]);offset=0;renderCharts();renderRows();updateExploreStatus();renderSamples();}
function sumBy(index){const result={};for(const g of groups)result[g[index]]=(result[g[index]]||0)+g[3];return result;}
function renderCharts(){const total=groups.reduce((n,g)=>n+g[3],0);$('filteredCount').textContent=fmt(total)+' / '+fmt(data.tables[table].count)+' records';const days=sumBy(0),agents=sumBy(1),kinds=sumBy(2),buckets={};const scale=$('granularity').value;for(const [day,count] of Object.entries(days)){if(!day)continue;let key=day;if(scale==='month')key=day.slice(0,7);if(scale==='week'){const d=new Date(day+'T00:00:00Z');d.setUTCDate(d.getUTCDate()-(d.getUTCDay()+6)%7);key=d.toISOString().slice(0,10);}buckets[key]=(buckets[key]||0)+count;}const entries=Object.entries(buckets).sort((a,b)=>a[0].localeCompare(b[0])),max=Math.max(1,...entries.map(x=>x[1]));$('timeline').replaceChildren();for(const [day,count] of entries){const bar=document.createElement('button');bar.style.height=Math.max(2,count/max*100)+'%';bar.title=(scale==='week'?'Week of ':'')+day+': '+fmt(count)+' records';bar.setAttribute('aria-label',bar.title);bar.onclick=()=>{let from=day,to=day;if(scale==='month'){from=day+'-01';const d=new Date(from+'T00:00:00Z');d.setUTCMonth(d.getUTCMonth()+1);d.setUTCDate(0);to=d.toISOString().slice(0,10);}if(scale==='week'){const d=new Date(day+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+6);to=d.toISOString().slice(0,10);}$('from').value=from;$('to').value=to;apply();};$('timeline').append(bar);}if(!entries.length)$('timeline').append(text('p',total?'No creation dates for these records.':'No records match your filters.'));$('dateLabels').replaceChildren(text('span',entries[0]?.[0]||''),text('span',entries.at(-1)?.[0]||''));bars('agentChart',agents,agentName,id=>{if(!id)return;$('agent').value=$('agent').value===id?'':id;apply();});bars('kindChart',kinds,k=>k||'Not categorized',k=>{if(!k)return;$('kind').value=$('kind').value===k?'':k;apply();});const topAgent=Object.entries(agents).filter(x=>x[0]).sort((a,b)=>b[1]-a[1])[0],topDay=Object.entries(days).filter(x=>x[0]).sort((a,b)=>b[1]-a[1])[0];$('insights').replaceChildren();for(const [label,value] of [['Most records by one agent',topAgent?agentName(topAgent[0])+' · '+fmt(topAgent[1]):'No agent-linked records'],['Busiest recorded day',topDay?topDay[0]+' · '+fmt(topDay[1]):'No dated records'],['Days with records',fmt(Object.keys(days).filter(Boolean).length)]]){const row=text('div','','insight');row.append(text('span',label),text('strong',value));$('insights').append(row);}if(table==='computer_use_turns')$('insights').append(text('p',fmt(data.tables[table].redacted_screenshots)+' turns have a redaction flag in the full table.','small'));}
function bars(target,counts,label,onClick){$(target).replaceChildren();const entries=Object.entries(counts).sort((a,b)=>b[1]-a[1]);for(const [key,count] of entries){const b=text('button','','agentrow'),row=text('div','');row.append(text('span',label(key)),text('span',fmt(count)));const track=text('div','','track'),fill=document.createElement('i');fill.style.width=count/entries[0][1]*100+'%';track.append(fill);b.append(row,track);b.onclick=()=>onClick(key);if(!key)b.disabled=true;$(target).append(b);}if(!entries.length)$(target).append(text('p','No matching records.','small'));}
function renderRows(){const page=groups.slice(offset,offset+pageSize);$('resultTitle').textContent='Daily breakdown · '+fmt(groups.length)+' groups';$('progress').textContent=page.length?'Showing '+fmt(offset+1)+'–'+fmt(offset+page.length)+' · newest dates first':'No groups match these filters. Use Reset to see the full table.';$('previous').disabled=offset===0;$('next').disabled=offset+pageSize>=groups.length;$('records').replaceChildren();for(const g of page){const [day,agent,kind,count]=g,b=text('button','','record aggregateRow');b.append(text('span',day||'No date'),text('strong',agentName(agent)),text('span',kind||'Not categorized'),text('strong',fmt(count)+(count===1?' record':' records')+' · Details','recordCount'));b.onclick=()=>openGroup(g);$('records').append(b);}}
function openGroup([day,agent,kind,count]){$('detailLabel').textContent='DAILY ACTIVITY GROUP';$('detailNote').textContent='This row summarizes source records; it does not contain their individual text. Read available examples in Reviewed records. Counts do not establish goal success.';$('detailTitle').textContent=(day||'Undated records')+' · '+fmt(count)+' records';$('readable').replaceChildren(text('p',title(table)),text('h3',agentName(agent)),text('p',data.agents[agent]?.model||'No AI-agent identity is assigned to this group.'),text('p',kind||'No action category'),text('p',meanings[kind]||descriptions[table]||''));$('related').replaceChildren();const source=text('a','Open source table on Hugging Face','button');source.href='https://huggingface.co/datasets/aidigestorg/ai-village/blob/'+data.revision+'/'+encodeURIComponent(table)+'.jsonl.gz';source.target='_blank';source.rel='noreferrer';$('related').append(source);if(agent){const b=text('button','Explore this agent','primary');b.onclick=()=>exploreGroup('agent',agent);$('related').append(b);}if(day){const b=text('button','Explore this day');b.onclick=()=>exploreGroup('day',day);$('related').append(b);}const matching=reviewed.records.filter(r=>r.table===table&&r.date.slice(0,10)===day&&r.agent===agent&&r.kind===kind);for(const record of matching){const read=text('button','Read reviewed example','primary');read.onclick=()=>openReviewed(record);$('related').append(read);}$('detail').showModal();}
$('filters').onsubmit=e=>{e.preventDefault();apply();};$('clear').onclick=()=>{$('filters').reset();$('sampleQuery').value='';apply();};$('granularity').onchange=renderCharts;$('previous').onclick=()=>{offset=Math.max(0,offset-pageSize);renderRows();};$('next').onclick=()=>{offset+=pageSize;renderRows();};$('closeDetail').onclick=()=>$('detail').close();boot();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_dataset_status',description:'Read the loaded public dataset summary and the selected table.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async()=>({loaded:!!data,source:data?.source,revision:data?.revision,table,matchingRecords:groups.reduce((n,g)=>n+g[3],0)})})).catch(()=>{});}catch{}}

function renderSamples(){
 const q=$('sampleQuery').value.trim().toLowerCase(),all=reviewed.records.filter(r=>r.table===table);
 const matching=all.filter(r=>(!$('agent').value||r.agent===$('agent').value)&&(!$('kind').value||r.kind===$('kind').value)&&(!$('from').value||r.date.slice(0,10)>=$('from').value)&&(!$('to').value||r.date.slice(0,10)<=$('to').value)&&(!q||r.content.toLowerCase().includes(q))&&(!$('query').value.trim()||[r.date,agentName(r.agent),r.kind].join(' ').toLowerCase().includes($('query').value.trim().toLowerCase()))).sort((a,b)=>b.date.localeCompare(a.date));
 $('sampleTitle').textContent='Reviewed records · '+matching.length+' available';$('sampleStatus').textContent=sampleLoadError||(all.length?(matching.length?'Showing '+(showAllSamples?matching.length:Math.min(3,matching.length))+' of '+matching.length+' reviewed examples matching these filters.':'No reviewed examples match these filters. Reset the filters to see this table’s published selection.'):'No reviewed contents have been published for this table yet. Full-table statistics are available below.');
 $('toggleSamples').hidden=matching.length<=3;$('toggleSamples').textContent=showAllSamples?'Show fewer examples':'Show all '+matching.length+' examples';$('sampleList').replaceChildren();
 for(const r of (showAllSamples?matching:matching.slice(0,3))){const b=text('button','','record sampleRecord'),meta=text('div','','recordmeta');meta.append(text('strong',agentName(r.agent)),text('span',r.date.slice(0,19)+' UTC'),text('span',r.form));b.append(meta,text('div',r.content.slice(0,220)+(r.content.length>220?'…':''),'recordtext'),text('span','Open record','openRecordLabel'));b.onclick=()=>openReviewed(r);$('sampleList').append(b);}
}
function openReviewed(r){
 $('detailLabel').textContent='REVIEWED SOURCE RECORD · '+r.form.toUpperCase();$('detailTitle').textContent=title(r.table)+' · '+agentName(r.agent);$('detailNote').textContent=r.review_note+' Agent statements and generated summaries are not independently verified.';
 $('readable').replaceChildren(text('p',r.date+' UTC'),text('p','Record ID: '+r.id,'small'),text('p','Source field: '+r.field+' · Snapshot '+reviewed.revision.slice(0,8),'small'),text('pre',r.content,'sourceContent'));$('related').replaceChildren();
 const source=text('a','Open source table on Hugging Face','button');source.href='https://huggingface.co/datasets/aidigestorg/ai-village/blob/'+reviewed.revision+'/'+encodeURIComponent(r.table)+'.jsonl.gz';source.target='_blank';source.rel='noreferrer';$('related').append(source);if(!$('detail').open)$('detail').showModal();
}
$('toggleSamples').onclick=()=>{showAllSamples=!showAllSamples;renderSamples();};$('sampleQuery').oninput=renderSamples;

function updateExploreStatus(){
 const count=groups.reduce((n,g)=>n+g[3],0),parts=[];
 if($('agent').value)parts.push('agent '+agentName($('agent').value));
 if($('from').value||$('to').value)parts.push($('from').value===$('to').value?'date '+$('from').value:($('from').value||'start')+' to '+($('to').value||'latest'));
 if($('kind').value)parts.push('category '+$('kind').value);
 if($('query').value.trim())parts.push('search “'+$('query').value.trim()+'”');
 $('exploreStatus').textContent='Showing '+fmt(count)+' records in '+title(table)+(parts.length?' · '+parts.join(' · '):' · all agents and dates')+'.';
 $('exploreStatus').hidden=false;
}
function exploreGroup(target,value){
 $('detail').close();$('filters').reset();if($('sampleQuery'))$('sampleQuery').value='';
 if(target==='agent')$('agent').value=value;
 else{$('from').value=value;$('to').value=value;}
 apply();
 requestAnimationFrame(()=>{$('exploreStatus').focus({preventScroll:true});$('filters').scrollIntoView({block:'start',behavior:'auto'});});
}
